// Mocks generated by Mockito 5.4.6 from annotations
// in mcal/test/sync_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mcal/api.dart' as _i5;
import 'package:mcal/frb_generated.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [RustLibApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockRustLibApi extends _i1.Mock implements _i2.RustLibApi {
  MockRustLibApi() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<int> crateApiAdd({required int? left, required int? right}) =>
      (super.noSuchMethod(
            Invocation.method(#crateApiAdd, [], {#left: left, #right: right}),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<String> crateApiGitAddAll({required String? path}) =>
      (super.noSuchMethod(
            Invocation.method(#crateApiGitAddAll, [], {#path: path}),
            returnValue: _i3.Future<String>.value(
              _i4.dummyValue<String>(
                this,
                Invocation.method(#crateApiGitAddAll, [], {#path: path}),
              ),
            ),
          )
          as _i3.Future<String>);

  @override
  _i3.Future<String> crateApiGitAddRemote({
    required String? path,
    required String? name,
    required String? url,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#crateApiGitAddRemote, [], {
              #path: path,
              #name: name,
              #url: url,
            }),
            returnValue: _i3.Future<String>.value(
              _i4.dummyValue<String>(
                this,
                Invocation.method(#crateApiGitAddRemote, [], {
                  #path: path,
                  #name: name,
                  #url: url,
                }),
              ),
            ),
          )
          as _i3.Future<String>);

  @override
  _i3.Future<String> crateApiGitCheckout({
    required String? path,
    required String? branch,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#crateApiGitCheckout, [], {
              #path: path,
              #branch: branch,
            }),
            returnValue: _i3.Future<String>.value(
              _i4.dummyValue<String>(
                this,
                Invocation.method(#crateApiGitCheckout, [], {
                  #path: path,
                  #branch: branch,
                }),
              ),
            ),
          )
          as _i3.Future<String>);

  @override
  _i3.Future<String> crateApiGitClone({
    required String? url,
    required String? path,
    String? username,
    String? password,
    String? sshKeyPath,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#crateApiGitClone, [], {
              #url: url,
              #path: path,
              #username: username,
              #password: password,
              #sshKeyPath: sshKeyPath,
            }),
            returnValue: _i3.Future<String>.value(
              _i4.dummyValue<String>(
                this,
                Invocation.method(#crateApiGitClone, [], {
                  #url: url,
                  #path: path,
                  #username: username,
                  #password: password,
                  #sshKeyPath: sshKeyPath,
                }),
              ),
            ),
          )
          as _i3.Future<String>);

  @override
  _i3.Future<String> crateApiGitCommit({
    required String? path,
    required String? message,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#crateApiGitCommit, [], {
              #path: path,
              #message: message,
            }),
            returnValue: _i3.Future<String>.value(
              _i4.dummyValue<String>(
                this,
                Invocation.method(#crateApiGitCommit, [], {
                  #path: path,
                  #message: message,
                }),
              ),
            ),
          )
          as _i3.Future<String>);

  @override
  _i3.Future<String> crateApiGitCurrentBranch({required String? path}) =>
      (super.noSuchMethod(
            Invocation.method(#crateApiGitCurrentBranch, [], {#path: path}),
            returnValue: _i3.Future<String>.value(
              _i4.dummyValue<String>(
                this,
                Invocation.method(#crateApiGitCurrentBranch, [], {#path: path}),
              ),
            ),
          )
          as _i3.Future<String>);

  @override
  _i3.Future<String> crateApiGitDiff({required String? path}) =>
      (super.noSuchMethod(
            Invocation.method(#crateApiGitDiff, [], {#path: path}),
            returnValue: _i3.Future<String>.value(
              _i4.dummyValue<String>(
                this,
                Invocation.method(#crateApiGitDiff, [], {#path: path}),
              ),
            ),
          )
          as _i3.Future<String>);

  @override
  _i3.Future<String> crateApiGitFetch({
    required String? path,
    required String? remote,
    String? username,
    String? password,
    String? sshKeyPath,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#crateApiGitFetch, [], {
              #path: path,
              #remote: remote,
              #username: username,
              #password: password,
              #sshKeyPath: sshKeyPath,
            }),
            returnValue: _i3.Future<String>.value(
              _i4.dummyValue<String>(
                this,
                Invocation.method(#crateApiGitFetch, [], {
                  #path: path,
                  #remote: remote,
                  #username: username,
                  #password: password,
                  #sshKeyPath: sshKeyPath,
                }),
              ),
            ),
          )
          as _i3.Future<String>);

  @override
  _i3.Future<String> crateApiGitInit({required String? path}) =>
      (super.noSuchMethod(
            Invocation.method(#crateApiGitInit, [], {#path: path}),
            returnValue: _i3.Future<String>.value(
              _i4.dummyValue<String>(
                this,
                Invocation.method(#crateApiGitInit, [], {#path: path}),
              ),
            ),
          )
          as _i3.Future<String>);

  @override
  _i3.Future<List<String>> crateApiGitListBranches({required String? path}) =>
      (super.noSuchMethod(
            Invocation.method(#crateApiGitListBranches, [], {#path: path}),
            returnValue: _i3.Future<List<String>>.value(<String>[]),
          )
          as _i3.Future<List<String>>);

  @override
  _i3.Future<String> crateApiGitMergeAbort({required String? path}) =>
      (super.noSuchMethod(
            Invocation.method(#crateApiGitMergeAbort, [], {#path: path}),
            returnValue: _i3.Future<String>.value(
              _i4.dummyValue<String>(
                this,
                Invocation.method(#crateApiGitMergeAbort, [], {#path: path}),
              ),
            ),
          )
          as _i3.Future<String>);

  @override
  _i3.Future<String> crateApiGitMergePreferRemote({required String? path}) =>
      (super.noSuchMethod(
            Invocation.method(#crateApiGitMergePreferRemote, [], {#path: path}),
            returnValue: _i3.Future<String>.value(
              _i4.dummyValue<String>(
                this,
                Invocation.method(#crateApiGitMergePreferRemote, [], {
                  #path: path,
                }),
              ),
            ),
          )
          as _i3.Future<String>);

  @override
  _i3.Future<String> crateApiGitPull({
    required String? path,
    String? username,
    String? password,
    String? sshKeyPath,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#crateApiGitPull, [], {
              #path: path,
              #username: username,
              #password: password,
              #sshKeyPath: sshKeyPath,
            }),
            returnValue: _i3.Future<String>.value(
              _i4.dummyValue<String>(
                this,
                Invocation.method(#crateApiGitPull, [], {
                  #path: path,
                  #username: username,
                  #password: password,
                  #sshKeyPath: sshKeyPath,
                }),
              ),
            ),
          )
          as _i3.Future<String>);

  @override
  _i3.Future<String> crateApiGitPush({
    required String? path,
    String? username,
    String? password,
    String? sshKeyPath,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#crateApiGitPush, [], {
              #path: path,
              #username: username,
              #password: password,
              #sshKeyPath: sshKeyPath,
            }),
            returnValue: _i3.Future<String>.value(
              _i4.dummyValue<String>(
                this,
                Invocation.method(#crateApiGitPush, [], {
                  #path: path,
                  #username: username,
                  #password: password,
                  #sshKeyPath: sshKeyPath,
                }),
              ),
            ),
          )
          as _i3.Future<String>);

  @override
  _i3.Future<String> crateApiGitStash({required String? path}) =>
      (super.noSuchMethod(
            Invocation.method(#crateApiGitStash, [], {#path: path}),
            returnValue: _i3.Future<String>.value(
              _i4.dummyValue<String>(
                this,
                Invocation.method(#crateApiGitStash, [], {#path: path}),
              ),
            ),
          )
          as _i3.Future<String>);

  @override
  _i3.Future<List<_i5.StatusEntry>> crateApiGitStatus({
    required String? path,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#crateApiGitStatus, [], {#path: path}),
            returnValue: _i3.Future<List<_i5.StatusEntry>>.value(
              <_i5.StatusEntry>[],
            ),
          )
          as _i3.Future<List<_i5.StatusEntry>>);

  @override
  _i3.Future<void> crateApiInitApp() =>
      (super.noSuchMethod(
            Invocation.method(#crateApiInitApp, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> crateApiSetSslCaCerts({required List<String>? pemCerts}) =>
      (super.noSuchMethod(
            Invocation.method(#crateApiSetSslCaCerts, [], {
              #pemCerts: pemCerts,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
