// Mocks generated by Mockito 5.4.6 from annotations
// in mcal/test/widget_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mcal/rust_api.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [RustLibApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockRustLibApi extends _i1.Mock implements _i2.RustLibApi {
  MockRustLibApi() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<int> add({required int? a, required int? b}) =>
      (super.noSuchMethod(
            Invocation.method(#add, [], {#a: a, #b: b}),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<String> gitInit({required String? path}) =>
      (super.noSuchMethod(
            Invocation.method(#gitInit, [], {#path: path}),
            returnValue: _i3.Future<String>.value(
              _i4.dummyValue<String>(
                this,
                Invocation.method(#gitInit, [], {#path: path}),
              ),
            ),
          )
          as _i3.Future<String>);

  @override
  _i3.Future<String> gitClone({
    required String? url,
    required String? path,
    String? username,
    String? password,
    String? sshKeyPath,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#gitClone, [], {
              #url: url,
              #path: path,
              #username: username,
              #password: password,
              #sshKeyPath: sshKeyPath,
            }),
            returnValue: _i3.Future<String>.value(
              _i4.dummyValue<String>(
                this,
                Invocation.method(#gitClone, [], {
                  #url: url,
                  #path: path,
                  #username: username,
                  #password: password,
                  #sshKeyPath: sshKeyPath,
                }),
              ),
            ),
          )
          as _i3.Future<String>);

  @override
  _i3.Future<String> gitPull({
    required String? path,
    String? username,
    String? password,
    String? sshKeyPath,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#gitPull, [], {
              #path: path,
              #username: username,
              #password: password,
              #sshKeyPath: sshKeyPath,
            }),
            returnValue: _i3.Future<String>.value(
              _i4.dummyValue<String>(
                this,
                Invocation.method(#gitPull, [], {
                  #path: path,
                  #username: username,
                  #password: password,
                  #sshKeyPath: sshKeyPath,
                }),
              ),
            ),
          )
          as _i3.Future<String>);

  @override
  _i3.Future<String> gitPush({
    required String? path,
    String? username,
    String? password,
    String? sshKeyPath,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#gitPush, [], {
              #path: path,
              #username: username,
              #password: password,
              #sshKeyPath: sshKeyPath,
            }),
            returnValue: _i3.Future<String>.value(
              _i4.dummyValue<String>(
                this,
                Invocation.method(#gitPush, [], {
                  #path: path,
                  #username: username,
                  #password: password,
                  #sshKeyPath: sshKeyPath,
                }),
              ),
            ),
          )
          as _i3.Future<String>);

  @override
  _i3.Future<String> gitStatus({required String? path}) =>
      (super.noSuchMethod(
            Invocation.method(#gitStatus, [], {#path: path}),
            returnValue: _i3.Future<String>.value(
              _i4.dummyValue<String>(
                this,
                Invocation.method(#gitStatus, [], {#path: path}),
              ),
            ),
          )
          as _i3.Future<String>);

  @override
  _i3.Future<String> gitAddRemote({
    required String? path,
    required String? name,
    required String? url,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#gitAddRemote, [], {
              #path: path,
              #name: name,
              #url: url,
            }),
            returnValue: _i3.Future<String>.value(
              _i4.dummyValue<String>(
                this,
                Invocation.method(#gitAddRemote, [], {
                  #path: path,
                  #name: name,
                  #url: url,
                }),
              ),
            ),
          )
          as _i3.Future<String>);

  @override
  _i3.Future<String> gitFetch({
    required String? path,
    required String? remote,
    String? username,
    String? password,
    String? sshKeyPath,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#gitFetch, [], {
              #path: path,
              #remote: remote,
              #username: username,
              #password: password,
              #sshKeyPath: sshKeyPath,
            }),
            returnValue: _i3.Future<String>.value(
              _i4.dummyValue<String>(
                this,
                Invocation.method(#gitFetch, [], {
                  #path: path,
                  #remote: remote,
                  #username: username,
                  #password: password,
                  #sshKeyPath: sshKeyPath,
                }),
              ),
            ),
          )
          as _i3.Future<String>);

  @override
  _i3.Future<String> gitCheckout({
    required String? path,
    required String? branch,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#gitCheckout, [], {#path: path, #branch: branch}),
            returnValue: _i3.Future<String>.value(
              _i4.dummyValue<String>(
                this,
                Invocation.method(#gitCheckout, [], {
                  #path: path,
                  #branch: branch,
                }),
              ),
            ),
          )
          as _i3.Future<String>);

  @override
  _i3.Future<String> gitAddAll({required String? path}) =>
      (super.noSuchMethod(
            Invocation.method(#gitAddAll, [], {#path: path}),
            returnValue: _i3.Future<String>.value(
              _i4.dummyValue<String>(
                this,
                Invocation.method(#gitAddAll, [], {#path: path}),
              ),
            ),
          )
          as _i3.Future<String>);

  @override
  _i3.Future<String> gitCommit({
    required String? path,
    required String? message,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#gitCommit, [], {#path: path, #message: message}),
            returnValue: _i3.Future<String>.value(
              _i4.dummyValue<String>(
                this,
                Invocation.method(#gitCommit, [], {
                  #path: path,
                  #message: message,
                }),
              ),
            ),
          )
          as _i3.Future<String>);

  @override
  _i3.Future<String> gitMergePreferRemote({required String? path}) =>
      (super.noSuchMethod(
            Invocation.method(#gitMergePreferRemote, [], {#path: path}),
            returnValue: _i3.Future<String>.value(
              _i4.dummyValue<String>(
                this,
                Invocation.method(#gitMergePreferRemote, [], {#path: path}),
              ),
            ),
          )
          as _i3.Future<String>);

  @override
  _i3.Future<String> gitMergeAbort({required String? path}) =>
      (super.noSuchMethod(
            Invocation.method(#gitMergeAbort, [], {#path: path}),
            returnValue: _i3.Future<String>.value(
              _i4.dummyValue<String>(
                this,
                Invocation.method(#gitMergeAbort, [], {#path: path}),
              ),
            ),
          )
          as _i3.Future<String>);
}
