// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'api.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `get_credentials`, `git_add_all_impl`, `git_add_remote_impl`, `git_checkout_impl`, `git_commit_impl`, `git_diff_impl`, `git_fetch_impl`, `git_init_impl`, `git_merge_abort_impl`, `git_merge_prefer_remote_impl`, `git_pull_impl`, `git_push_impl`, `git_stash_impl`, `git_status_impl`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `fmt`, `fmt`, `from`, `from`

Future<int> add({required int left, required int right}) =>
    RustLib.instance.api.crateApiAdd(left: left, right: right);

Future<String> gitInit({required String path}) =>
    RustLib.instance.api.crateApiGitInit(path: path);

Future<String> gitClone({
  required String url,
  required String path,
  String? username,
  String? password,
  String? sshKeyPath,
}) => RustLib.instance.api.crateApiGitClone(
  url: url,
  path: path,
  username: username,
  password: password,
  sshKeyPath: sshKeyPath,
);

Future<String> gitCurrentBranch({required String path}) =>
    RustLib.instance.api.crateApiGitCurrentBranch(path: path);

Future<List<String>> gitListBranches({required String path}) =>
    RustLib.instance.api.crateApiGitListBranches(path: path);

Future<String> gitPull({
  required String path,
  String? username,
  String? password,
  String? sshKeyPath,
}) => RustLib.instance.api.crateApiGitPull(
  path: path,
  username: username,
  password: password,
  sshKeyPath: sshKeyPath,
);

Future<String> gitPush({
  required String path,
  String? username,
  String? password,
  String? sshKeyPath,
}) => RustLib.instance.api.crateApiGitPush(
  path: path,
  username: username,
  password: password,
  sshKeyPath: sshKeyPath,
);

Future<List<StatusEntry>> gitStatus({required String path}) =>
    RustLib.instance.api.crateApiGitStatus(path: path);

Future<String> gitAddRemote({
  required String path,
  required String name,
  required String url,
}) =>
    RustLib.instance.api.crateApiGitAddRemote(path: path, name: name, url: url);

Future<String> gitFetch({
  required String path,
  required String remote,
  String? username,
  String? password,
  String? sshKeyPath,
}) => RustLib.instance.api.crateApiGitFetch(
  path: path,
  remote: remote,
  username: username,
  password: password,
  sshKeyPath: sshKeyPath,
);

Future<String> gitCheckout({required String path, required String branch}) =>
    RustLib.instance.api.crateApiGitCheckout(path: path, branch: branch);

Future<String> gitAddAll({required String path}) =>
    RustLib.instance.api.crateApiGitAddAll(path: path);

Future<String> gitCommit({required String path, required String message}) =>
    RustLib.instance.api.crateApiGitCommit(path: path, message: message);

Future<String> gitMergePreferRemote({required String path}) =>
    RustLib.instance.api.crateApiGitMergePreferRemote(path: path);

Future<String> gitMergeAbort({required String path}) =>
    RustLib.instance.api.crateApiGitMergeAbort(path: path);

Future<String> gitStash({required String path}) =>
    RustLib.instance.api.crateApiGitStash(path: path);

Future<String> gitDiff({required String path}) =>
    RustLib.instance.api.crateApiGitDiff(path: path);

@freezed
sealed class GitError with _$GitError implements FrbException {
  const GitError._();

  const factory GitError.io(String field0) = GitError_Io;
  const factory GitError.git(String field0) = GitError_Git;
  const factory GitError.auth(String field0) = GitError_Auth;
  const factory GitError.other(String field0) = GitError_Other;
}

class StatusEntry {
  final String path;
  final String status;

  const StatusEntry({required this.path, required this.status});

  @override
  int get hashCode => path.hashCode ^ status.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StatusEntry &&
          runtimeType == other.runtimeType &&
          path == other.path &&
          status == other.status;
}
