// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => 380905477;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'mcal_native',
        ioDirectory: 'native/target/release/',
        webPrefix: 'pkg/',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<int> crateApiAdd({required int left, required int right});

  Future<String> crateApiCreateEvent({
    required String title,
    required String description,
    required String startDate,
    String? endDate,
    String? startTime,
    String? endTime,
    required bool isAllDay,
    required String recurrence,
    required String calendarDir,
  });

  Future<void> crateApiDeleteEvent({
    required String id,
    required String calendarDir,
  });

  Future<bool> crateApiEventOccursOn({
    required EventDto event,
    required String date,
  });

  Future<List<EventDto>> crateApiGenerateInstances({
    required List<EventDto> events,
    required String startDate,
    required String endDate,
  });

  Future<List<EventDto>> crateApiGetAllEvents({required String calendarDir});

  Future<List<EventDto>> crateApiGetEventsInRange({
    required String startDate,
    required String endDate,
    required String calendarDir,
  });

  Future<String> crateApiGitAddAll({required String path});

  Future<String> crateApiGitAddRemote({
    required String path,
    required String name,
    required String url,
  });

  Future<String> crateApiGitCheckout({
    required String path,
    required String branch,
  });

  Future<String> crateApiGitClone({
    required String url,
    required String path,
    String? username,
    String? password,
    String? sshKeyPath,
  });

  Future<String> crateApiGitCommit({
    required String path,
    required String message,
  });

  Future<String> crateApiGitCurrentBranch({required String path});

  Future<String> crateApiGitDiff({required String path});

  Future<String> crateApiGitFetch({
    required String path,
    required String remote,
    String? username,
    String? password,
    String? sshKeyPath,
  });

  Future<bool> crateApiGitHasLocalChanges({required String path});

  Future<String> crateApiGitInit({required String path});

  Future<List<String>> crateApiGitListBranches({required String path});

  Future<String> crateApiGitMergeAbort({required String path});

  Future<String> crateApiGitMergePreferRemote({required String path});

  Future<String> crateApiGitPull({
    required String path,
    String? username,
    String? password,
    String? sshKeyPath,
  });

  Future<String> crateApiGitPush({
    required String path,
    String? username,
    String? password,
    String? sshKeyPath,
  });

  Future<String> crateApiGitRemoveRemote({
    required String path,
    required String name,
  });

  Future<String> crateApiGitStash({required String path});

  Future<List<StatusEntry>> crateApiGitStatus({required String path});

  Future<void> crateApiInitApp();

  Future<void> crateApiSetSslCaCerts({required List<String> pemCerts});

  Future<void> crateApiUpdateEvent({
    required String id,
    required String title,
    required String description,
    required String startDate,
    String? endDate,
    String? startTime,
    String? endTime,
    required bool isAllDay,
    required String recurrence,
    required String calendarDir,
  });

  Future<void> crateApiValidateEvent({
    required String title,
    required String startDate,
    String? endDate,
    String? startTime,
    String? endTime,
  });
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<int> crateApiAdd({required int left, required int right}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_32(left, serializer);
          sse_encode_i_32(right, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_i_32,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiAddConstMeta,
        argValues: [left, right],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAddConstMeta =>
      const TaskConstMeta(debugName: "add", argNames: ["left", "right"]);

  @override
  Future<String> crateApiCreateEvent({
    required String title,
    required String description,
    required String startDate,
    String? endDate,
    String? startTime,
    String? endTime,
    required bool isAllDay,
    required String recurrence,
    required String calendarDir,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(title, serializer);
          sse_encode_String(description, serializer);
          sse_encode_String(startDate, serializer);
          sse_encode_opt_String(endDate, serializer);
          sse_encode_opt_String(startTime, serializer);
          sse_encode_opt_String(endTime, serializer);
          sse_encode_bool(isAllDay, serializer);
          sse_encode_String(recurrence, serializer);
          sse_encode_String(calendarDir, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiCreateEventConstMeta,
        argValues: [
          title,
          description,
          startDate,
          endDate,
          startTime,
          endTime,
          isAllDay,
          recurrence,
          calendarDir,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCreateEventConstMeta => const TaskConstMeta(
    debugName: "create_event",
    argNames: [
      "title",
      "description",
      "startDate",
      "endDate",
      "startTime",
      "endTime",
      "isAllDay",
      "recurrence",
      "calendarDir",
    ],
  );

  @override
  Future<void> crateApiDeleteEvent({
    required String id,
    required String calendarDir,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(id, serializer);
          sse_encode_String(calendarDir, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiDeleteEventConstMeta,
        argValues: [id, calendarDir],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDeleteEventConstMeta => const TaskConstMeta(
    debugName: "delete_event",
    argNames: ["id", "calendarDir"],
  );

  @override
  Future<bool> crateApiEventOccursOn({
    required EventDto event,
    required String date,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_event_dto(event, serializer);
          sse_encode_String(date, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEventOccursOnConstMeta,
        argValues: [event, date],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEventOccursOnConstMeta => const TaskConstMeta(
    debugName: "event_occurs_on",
    argNames: ["event", "date"],
  );

  @override
  Future<List<EventDto>> crateApiGenerateInstances({
    required List<EventDto> events,
    required String startDate,
    required String endDate,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_event_dto(events, serializer);
          sse_encode_String(startDate, serializer);
          sse_encode_String(endDate, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_event_dto,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiGenerateInstancesConstMeta,
        argValues: [events, startDate, endDate],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGenerateInstancesConstMeta => const TaskConstMeta(
    debugName: "generate_instances",
    argNames: ["events", "startDate", "endDate"],
  );

  @override
  Future<List<EventDto>> crateApiGetAllEvents({required String calendarDir}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(calendarDir, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_event_dto,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiGetAllEventsConstMeta,
        argValues: [calendarDir],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGetAllEventsConstMeta => const TaskConstMeta(
    debugName: "get_all_events",
    argNames: ["calendarDir"],
  );

  @override
  Future<List<EventDto>> crateApiGetEventsInRange({
    required String startDate,
    required String endDate,
    required String calendarDir,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(startDate, serializer);
          sse_encode_String(endDate, serializer);
          sse_encode_String(calendarDir, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_event_dto,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiGetEventsInRangeConstMeta,
        argValues: [startDate, endDate, calendarDir],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGetEventsInRangeConstMeta => const TaskConstMeta(
    debugName: "get_events_in_range",
    argNames: ["startDate", "endDate", "calendarDir"],
  );

  @override
  Future<String> crateApiGitAddAll({required String path}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_git_error,
        ),
        constMeta: kCrateApiGitAddAllConstMeta,
        argValues: [path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGitAddAllConstMeta =>
      const TaskConstMeta(debugName: "git_add_all", argNames: ["path"]);

  @override
  Future<String> crateApiGitAddRemote({
    required String path,
    required String name,
    required String url,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          sse_encode_String(name, serializer);
          sse_encode_String(url, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_git_error,
        ),
        constMeta: kCrateApiGitAddRemoteConstMeta,
        argValues: [path, name, url],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGitAddRemoteConstMeta => const TaskConstMeta(
    debugName: "git_add_remote",
    argNames: ["path", "name", "url"],
  );

  @override
  Future<String> crateApiGitCheckout({
    required String path,
    required String branch,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          sse_encode_String(branch, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_git_error,
        ),
        constMeta: kCrateApiGitCheckoutConstMeta,
        argValues: [path, branch],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGitCheckoutConstMeta => const TaskConstMeta(
    debugName: "git_checkout",
    argNames: ["path", "branch"],
  );

  @override
  Future<String> crateApiGitClone({
    required String url,
    required String path,
    String? username,
    String? password,
    String? sshKeyPath,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(url, serializer);
          sse_encode_String(path, serializer);
          sse_encode_opt_String(username, serializer);
          sse_encode_opt_String(password, serializer);
          sse_encode_opt_String(sshKeyPath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_git_error,
        ),
        constMeta: kCrateApiGitCloneConstMeta,
        argValues: [url, path, username, password, sshKeyPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGitCloneConstMeta => const TaskConstMeta(
    debugName: "git_clone",
    argNames: ["url", "path", "username", "password", "sshKeyPath"],
  );

  @override
  Future<String> crateApiGitCommit({
    required String path,
    required String message,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          sse_encode_String(message, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_git_error,
        ),
        constMeta: kCrateApiGitCommitConstMeta,
        argValues: [path, message],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGitCommitConstMeta => const TaskConstMeta(
    debugName: "git_commit",
    argNames: ["path", "message"],
  );

  @override
  Future<String> crateApiGitCurrentBranch({required String path}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_git_error,
        ),
        constMeta: kCrateApiGitCurrentBranchConstMeta,
        argValues: [path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGitCurrentBranchConstMeta =>
      const TaskConstMeta(debugName: "git_current_branch", argNames: ["path"]);

  @override
  Future<String> crateApiGitDiff({required String path}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_git_error,
        ),
        constMeta: kCrateApiGitDiffConstMeta,
        argValues: [path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGitDiffConstMeta =>
      const TaskConstMeta(debugName: "git_diff", argNames: ["path"]);

  @override
  Future<String> crateApiGitFetch({
    required String path,
    required String remote,
    String? username,
    String? password,
    String? sshKeyPath,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          sse_encode_String(remote, serializer);
          sse_encode_opt_String(username, serializer);
          sse_encode_opt_String(password, serializer);
          sse_encode_opt_String(sshKeyPath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_git_error,
        ),
        constMeta: kCrateApiGitFetchConstMeta,
        argValues: [path, remote, username, password, sshKeyPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGitFetchConstMeta => const TaskConstMeta(
    debugName: "git_fetch",
    argNames: ["path", "remote", "username", "password", "sshKeyPath"],
  );

  @override
  Future<bool> crateApiGitHasLocalChanges({required String path}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 16,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_git_error,
        ),
        constMeta: kCrateApiGitHasLocalChangesConstMeta,
        argValues: [path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGitHasLocalChangesConstMeta => const TaskConstMeta(
    debugName: "git_has_local_changes",
    argNames: ["path"],
  );

  @override
  Future<String> crateApiGitInit({required String path}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 17,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_git_error,
        ),
        constMeta: kCrateApiGitInitConstMeta,
        argValues: [path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGitInitConstMeta =>
      const TaskConstMeta(debugName: "git_init", argNames: ["path"]);

  @override
  Future<List<String>> crateApiGitListBranches({required String path}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 18,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_String,
          decodeErrorData: sse_decode_git_error,
        ),
        constMeta: kCrateApiGitListBranchesConstMeta,
        argValues: [path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGitListBranchesConstMeta =>
      const TaskConstMeta(debugName: "git_list_branches", argNames: ["path"]);

  @override
  Future<String> crateApiGitMergeAbort({required String path}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 19,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_git_error,
        ),
        constMeta: kCrateApiGitMergeAbortConstMeta,
        argValues: [path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGitMergeAbortConstMeta =>
      const TaskConstMeta(debugName: "git_merge_abort", argNames: ["path"]);

  @override
  Future<String> crateApiGitMergePreferRemote({required String path}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 20,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_git_error,
        ),
        constMeta: kCrateApiGitMergePreferRemoteConstMeta,
        argValues: [path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGitMergePreferRemoteConstMeta =>
      const TaskConstMeta(
        debugName: "git_merge_prefer_remote",
        argNames: ["path"],
      );

  @override
  Future<String> crateApiGitPull({
    required String path,
    String? username,
    String? password,
    String? sshKeyPath,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          sse_encode_opt_String(username, serializer);
          sse_encode_opt_String(password, serializer);
          sse_encode_opt_String(sshKeyPath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 21,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_git_error,
        ),
        constMeta: kCrateApiGitPullConstMeta,
        argValues: [path, username, password, sshKeyPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGitPullConstMeta => const TaskConstMeta(
    debugName: "git_pull",
    argNames: ["path", "username", "password", "sshKeyPath"],
  );

  @override
  Future<String> crateApiGitPush({
    required String path,
    String? username,
    String? password,
    String? sshKeyPath,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          sse_encode_opt_String(username, serializer);
          sse_encode_opt_String(password, serializer);
          sse_encode_opt_String(sshKeyPath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 22,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_git_error,
        ),
        constMeta: kCrateApiGitPushConstMeta,
        argValues: [path, username, password, sshKeyPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGitPushConstMeta => const TaskConstMeta(
    debugName: "git_push",
    argNames: ["path", "username", "password", "sshKeyPath"],
  );

  @override
  Future<String> crateApiGitRemoveRemote({
    required String path,
    required String name,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          sse_encode_String(name, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 23,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_git_error,
        ),
        constMeta: kCrateApiGitRemoveRemoteConstMeta,
        argValues: [path, name],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGitRemoveRemoteConstMeta => const TaskConstMeta(
    debugName: "git_remove_remote",
    argNames: ["path", "name"],
  );

  @override
  Future<String> crateApiGitStash({required String path}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 24,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_git_error,
        ),
        constMeta: kCrateApiGitStashConstMeta,
        argValues: [path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGitStashConstMeta =>
      const TaskConstMeta(debugName: "git_stash", argNames: ["path"]);

  @override
  Future<List<StatusEntry>> crateApiGitStatus({required String path}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 25,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_status_entry,
          decodeErrorData: sse_decode_git_error,
        ),
        constMeta: kCrateApiGitStatusConstMeta,
        argValues: [path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGitStatusConstMeta =>
      const TaskConstMeta(debugName: "git_status", argNames: ["path"]);

  @override
  Future<void> crateApiInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 26,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  Future<void> crateApiSetSslCaCerts({required List<String> pemCerts}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_String(pemCerts, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 27,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_git_error,
        ),
        constMeta: kCrateApiSetSslCaCertsConstMeta,
        argValues: [pemCerts],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSetSslCaCertsConstMeta => const TaskConstMeta(
    debugName: "set_ssl_ca_certs",
    argNames: ["pemCerts"],
  );

  @override
  Future<void> crateApiUpdateEvent({
    required String id,
    required String title,
    required String description,
    required String startDate,
    String? endDate,
    String? startTime,
    String? endTime,
    required bool isAllDay,
    required String recurrence,
    required String calendarDir,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(id, serializer);
          sse_encode_String(title, serializer);
          sse_encode_String(description, serializer);
          sse_encode_String(startDate, serializer);
          sse_encode_opt_String(endDate, serializer);
          sse_encode_opt_String(startTime, serializer);
          sse_encode_opt_String(endTime, serializer);
          sse_encode_bool(isAllDay, serializer);
          sse_encode_String(recurrence, serializer);
          sse_encode_String(calendarDir, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 28,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiUpdateEventConstMeta,
        argValues: [
          id,
          title,
          description,
          startDate,
          endDate,
          startTime,
          endTime,
          isAllDay,
          recurrence,
          calendarDir,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiUpdateEventConstMeta => const TaskConstMeta(
    debugName: "update_event",
    argNames: [
      "id",
      "title",
      "description",
      "startDate",
      "endDate",
      "startTime",
      "endTime",
      "isAllDay",
      "recurrence",
      "calendarDir",
    ],
  );

  @override
  Future<void> crateApiValidateEvent({
    required String title,
    required String startDate,
    String? endDate,
    String? startTime,
    String? endTime,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(title, serializer);
          sse_encode_String(startDate, serializer);
          sse_encode_opt_String(endDate, serializer);
          sse_encode_opt_String(startTime, serializer);
          sse_encode_opt_String(endTime, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 29,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiValidateEventConstMeta,
        argValues: [title, startDate, endDate, startTime, endTime],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiValidateEventConstMeta => const TaskConstMeta(
    debugName: "validate_event",
    argNames: ["title", "startDate", "endDate", "startTime", "endTime"],
  );

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  EventDto dco_decode_box_autoadd_event_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_event_dto(raw);
  }

  @protected
  EventDto dco_decode_event_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 10)
      throw Exception('unexpected arr length: expect 10 but see ${arr.length}');
    return EventDto(
      id: dco_decode_String(arr[0]),
      title: dco_decode_String(arr[1]),
      description: dco_decode_String(arr[2]),
      startDate: dco_decode_String(arr[3]),
      endDate: dco_decode_opt_String(arr[4]),
      startTime: dco_decode_opt_String(arr[5]),
      endTime: dco_decode_opt_String(arr[6]),
      isAllDay: dco_decode_bool(arr[7]),
      recurrence: dco_decode_String(arr[8]),
      isRecurringInstance: dco_decode_bool(arr[9]),
    );
  }

  @protected
  GitError dco_decode_git_error(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return GitError_Io(dco_decode_String(raw[1]));
      case 1:
        return GitError_Git(dco_decode_String(raw[1]));
      case 2:
        return GitError_Auth(dco_decode_String(raw[1]));
      case 3:
        return GitError_Other(dco_decode_String(raw[1]));
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<EventDto> dco_decode_list_event_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_event_dto).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<StatusEntry> dco_decode_list_status_entry(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_status_entry).toList();
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  StatusEntry dco_decode_status_entry(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return StatusEntry(
      path: dco_decode_String(arr[0]),
      status: dco_decode_String(arr[1]),
    );
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  EventDto sse_decode_box_autoadd_event_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_event_dto(deserializer));
  }

  @protected
  EventDto sse_decode_event_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_title = sse_decode_String(deserializer);
    var var_description = sse_decode_String(deserializer);
    var var_startDate = sse_decode_String(deserializer);
    var var_endDate = sse_decode_opt_String(deserializer);
    var var_startTime = sse_decode_opt_String(deserializer);
    var var_endTime = sse_decode_opt_String(deserializer);
    var var_isAllDay = sse_decode_bool(deserializer);
    var var_recurrence = sse_decode_String(deserializer);
    var var_isRecurringInstance = sse_decode_bool(deserializer);
    return EventDto(
      id: var_id,
      title: var_title,
      description: var_description,
      startDate: var_startDate,
      endDate: var_endDate,
      startTime: var_startTime,
      endTime: var_endTime,
      isAllDay: var_isAllDay,
      recurrence: var_recurrence,
      isRecurringInstance: var_isRecurringInstance,
    );
  }

  @protected
  GitError sse_decode_git_error(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        var var_field0 = sse_decode_String(deserializer);
        return GitError_Io(var_field0);
      case 1:
        var var_field0 = sse_decode_String(deserializer);
        return GitError_Git(var_field0);
      case 2:
        var var_field0 = sse_decode_String(deserializer);
        return GitError_Auth(var_field0);
      case 3:
        var var_field0 = sse_decode_String(deserializer);
        return GitError_Other(var_field0);
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<EventDto> sse_decode_list_event_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <EventDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_event_dto(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<StatusEntry> sse_decode_list_status_entry(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <StatusEntry>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_status_entry(deserializer));
    }
    return ans_;
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  StatusEntry sse_decode_status_entry(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_path = sse_decode_String(deserializer);
    var var_status = sse_decode_String(deserializer);
    return StatusEntry(path: var_path, status: var_status);
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_event_dto(
    EventDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_event_dto(self, serializer);
  }

  @protected
  void sse_encode_event_dto(EventDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.title, serializer);
    sse_encode_String(self.description, serializer);
    sse_encode_String(self.startDate, serializer);
    sse_encode_opt_String(self.endDate, serializer);
    sse_encode_opt_String(self.startTime, serializer);
    sse_encode_opt_String(self.endTime, serializer);
    sse_encode_bool(self.isAllDay, serializer);
    sse_encode_String(self.recurrence, serializer);
    sse_encode_bool(self.isRecurringInstance, serializer);
  }

  @protected
  void sse_encode_git_error(GitError self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case GitError_Io(field0: final field0):
        sse_encode_i_32(0, serializer);
        sse_encode_String(field0, serializer);
      case GitError_Git(field0: final field0):
        sse_encode_i_32(1, serializer);
        sse_encode_String(field0, serializer);
      case GitError_Auth(field0: final field0):
        sse_encode_i_32(2, serializer);
        sse_encode_String(field0, serializer);
      case GitError_Other(field0: final field0):
        sse_encode_i_32(3, serializer);
        sse_encode_String(field0, serializer);
    }
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_event_dto(
    List<EventDto> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_event_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_status_entry(
    List<StatusEntry> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_status_entry(item, serializer);
    }
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_status_entry(StatusEntry self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.path, serializer);
    sse_encode_String(self.status, serializer);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }
}
