// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'dart:async';
import 'dart:convert';
import 'frb_generated.io.dart' if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';


                /// Main entrypoint of the Rust API
                class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
                  @internal
                  static final instance = RustLib._();

                  RustLib._();

                  /// Initialize flutter_rust_bridge
                  static Future<void> init({
                    RustLibApi? api,
                    BaseHandler? handler,
                    ExternalLibrary? externalLibrary,
                    bool forceSameCodegenVersion = true,
                  }) async {
                    await instance.initImpl(
                      api: api,
                      handler: handler,
                      externalLibrary: externalLibrary,
                      forceSameCodegenVersion: forceSameCodegenVersion,
                    );
                  }

                  /// Initialize flutter_rust_bridge in mock mode.
                  /// No libraries for FFI are loaded.
                  static void initMock({
                    required RustLibApi api,
                  }) {
                    instance.initMockImpl(
                      api: api,
                    );
                  }

                  /// Dispose flutter_rust_bridge
                  ///
                  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
                  /// is automatically disposed when the app stops.
                  static void dispose() => instance.disposeImpl();

                  @override
                  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor => RustLibApiImpl.new;

                  @override
                  WireConstructor<RustLibWire> get wireConstructor => RustLibWire.fromExternalLibrary;

                  @override
                  Future<void> executeRustInitializers() async {
                    
                  }

                  @override
                  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig => kDefaultExternalLibraryLoaderConfig;

                  @override
                  String get codegenVersion => '2.11.1';

                  @override
                  int get rustContentHash => -291292710;

                  static const kDefaultExternalLibraryLoaderConfig = ExternalLibraryLoaderConfig(
                    stem: 'mcal_native',
                    ioDirectory: 'native/target/release/',
                    webPrefix: 'pkg/',
                  );
                }
                

                abstract class RustLibApi extends BaseApi {
                  Future<int> add({required int a, required int b});
                  Future<String> gitInit({required String path});
                  Future<String> gitClone({required String url, required String path, String? username, String? password, String? sshKeyPath});
                  Future<String> gitPull({required String path, String? username, String? password, String? sshKeyPath});
                  Future<String> gitPush({required String path, String? username, String? password, String? sshKeyPath});
                  Future<String> gitStatus({required String path});
                  Future<String> gitAddRemote({required String path, required String name, required String url});
                  Future<String> gitFetch({required String path, required String remote, String? username, String? password, String? sshKeyPath});
                  Future<String> gitCheckout({required String path, required String branch});
                  Future<String> gitAddAll({required String path});
                  Future<String> gitCommit({required String path, required String message});
                  Future<String> gitMergePreferRemote({required String path});
                  Future<String> gitMergeAbort({required String path});
                }
                

                class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
                  RustLibApiImpl({
                    required super.handler,
                    required super.wire,
                    required super.generalizedFrbRustBinding,
                    required super.portManager,
                  });

                  @override
                  Future<int> add({required int a, required int b}) => throw UnimplementedError();

                  @override
                  Future<String> gitInit({required String path}) => throw UnimplementedError();

                  @override
                  Future<String> gitClone({required String url, required String path, String? username, String? password, String? sshKeyPath}) => throw UnimplementedError();

                  @override
                  Future<String> gitPull({required String path, String? username, String? password, String? sshKeyPath}) => throw UnimplementedError();

                  @override
                  Future<String> gitPush({required String path, String? username, String? password, String? sshKeyPath}) => throw UnimplementedError();

                  @override
                  Future<String> gitStatus({required String path}) => throw UnimplementedError();

                  @override
                  Future<String> gitAddRemote({required String path, required String name, required String url}) => throw UnimplementedError();

                  @override
                  Future<String> gitFetch({required String path, required String remote, String? username, String? password, String? sshKeyPath}) => throw UnimplementedError();

                  @override
                  Future<String> gitCheckout({required String path, required String branch}) => throw UnimplementedError();

                  @override
                  Future<String> gitAddAll({required String path}) => throw UnimplementedError();

                  @override
                  Future<String> gitCommit({required String path, required String message}) => throw UnimplementedError();

                  @override
                  Future<String> gitMergePreferRemote({required String path}) => throw UnimplementedError();

                  @override
                  Future<String> gitMergeAbort({required String path}) => throw UnimplementedError();

                  @protected int sse_decode_i_32(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
return deserializer.buffer.getInt32(); }

@protected bool sse_decode_bool(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
return deserializer.buffer.getUint8() != 0; }

@protected void sse_encode_i_32(int self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
serializer.buffer.putInt32(self); }

@protected void sse_encode_bool(bool self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
serializer.buffer.putUint8(self ? 1 : 0); }
                }
                
